# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Run build steps
RUN npm run build

EXPOSE 5305

CMD [ "node", "mcp/index.js", "." ]
